import { AuditEvent, GovernanceControl } from './types';

// ─── Audit Events ───────────────────────────────────────────────────────────

export const auditEvents: AuditEvent[] = [
  {
    id: 'evt-001',
    timestamp: '2024-04-15T14:32:00Z',
    actor: 'Sarah Chen',
    actorAvatar: 'SC',
    actionType: 'query_blocked',
    target: 'SELECT * FROM customers WHERE ssn IS NOT NULL',
    status: 'blocked',
  },
  {
    id: 'evt-002',
    timestamp: '2024-04-15T14:18:00Z',
    actor: 'Alex Rivera',
    actorAvatar: 'AR',
    actionType: 'metric_certified',
    target: 'Net Revenue Retention (NRR)',
    status: 'success',
  },
  {
    id: 'evt-003',
    timestamp: '2024-04-15T13:45:00Z',
    actor: 'System',
    actorAvatar: 'SY',
    actionType: 'rls_check',
    target: 'subscriptions table — team_id filter applied',
    status: 'success',
  },
  {
    id: 'evt-004',
    timestamp: '2024-04-15T12:58:00Z',
    actor: 'Jordan Park',
    actorAvatar: 'JP',
    actionType: 'pii_access',
    target: 'customers.email column',
    status: 'warning',
  },
  {
    id: 'evt-005',
    timestamp: '2024-04-15T11:22:00Z',
    actor: 'System',
    actorAvatar: 'SY',
    actionType: 'trace_logged',
    target: 'AI query: "Why did churn increase in April?"',
    status: 'success',
  },
  {
    id: 'evt-006',
    timestamp: '2024-04-15T10:05:00Z',
    actor: 'Maria Lopez',
    actorAvatar: 'ML',
    actionType: 'config_changed',
    target: 'PII Column Masking — enabled',
    status: 'success',
  },
  {
    id: 'evt-007',
    timestamp: '2024-04-14T16:42:00Z',
    actor: 'Alex Rivera',
    actorAvatar: 'AR',
    actionType: 'user_login',
    target: 'Workspace: Acme Corp',
    status: 'success',
  },
  {
    id: 'evt-008',
    timestamp: '2024-04-14T15:30:00Z',
    actor: 'Sarah Chen',
    actorAvatar: 'SC',
    actionType: 'export_data',
    target: 'subscriptions.csv — 24,853 rows',
    status: 'success',
  },
  {
    id: 'evt-009',
    timestamp: '2024-04-14T14:12:00Z',
    actor: 'System',
    actorAvatar: 'SY',
    actionType: 'query_blocked',
    target: 'DROP TABLE subscriptions',
    status: 'blocked',
  },
  {
    id: 'evt-010',
    timestamp: '2024-04-14T12:48:00Z',
    actor: 'Jordan Park',
    actorAvatar: 'JP',
    actionType: 'trace_logged',
    target: 'AI query: "MRR breakdown by plan"',
    status: 'success',
  },
  {
    id: 'evt-011',
    timestamp: '2024-04-14T11:15:00Z',
    actor: 'Maria Lopez',
    actorAvatar: 'ML',
    actionType: 'metric_certified',
    target: 'Monthly Recurring Revenue (MRR)',
    status: 'success',
  },
  {
    id: 'evt-012',
    timestamp: '2024-04-14T09:30:00Z',
    actor: 'Alex Rivera',
    actorAvatar: 'AR',
    actionType: 'rls_check',
    target: 'invoices table — org_id filter applied',
    status: 'success',
  },
  {
    id: 'evt-013',
    timestamp: '2024-04-13T17:20:00Z',
    actor: 'Sarah Chen',
    actorAvatar: 'SC',
    actionType: 'user_login',
    target: 'Workspace: Acme Corp',
    status: 'success',
  },
  {
    id: 'evt-014',
    timestamp: '2024-04-13T15:45:00Z',
    actor: 'System',
    actorAvatar: 'SY',
    actionType: 'query_blocked',
    target: 'UPDATE users SET role = admin WHERE 1=1',
    status: 'blocked',
  },
  {
    id: 'evt-015',
    timestamp: '2024-04-13T14:08:00Z',
    actor: 'Jordan Park',
    actorAvatar: 'JP',
    actionType: 'export_data',
    target: 'churn_analysis_report.csv — 1,204 rows',
    status: 'success',
  },
  {
    id: 'evt-016',
    timestamp: '2024-04-13T11:30:00Z',
    actor: 'Maria Lopez',
    actorAvatar: 'ML',
    actionType: 'pii_access',
    target: 'customers.phone column',
    status: 'warning',
  },
  {
    id: 'evt-017',
    timestamp: '2024-04-13T09:55:00Z',
    actor: 'Alex Rivera',
    actorAvatar: 'AR',
    actionType: 'config_changed',
    target: 'SQL Denylist — added pattern: TRUNCATE',
    status: 'success',
  },
  {
    id: 'evt-018',
    timestamp: '2024-04-12T16:10:00Z',
    actor: 'System',
    actorAvatar: 'SY',
    actionType: 'trace_logged',
    target: 'AI query: "Top expansion accounts this quarter"',
    status: 'success',
  },
];

// ─── Governance Controls ────────────────────────────────────────────────────

export const governanceControls: GovernanceControl[] = [
  {
    id: 'gov-001',
    label: 'SQL Denylist Enforcement',
    description: 'Block dangerous SQL patterns (DROP, TRUNCATE, DELETE without WHERE)',
    enabled: true,
  },
  {
    id: 'gov-002',
    label: 'PII Column Masking',
    description: 'Automatically mask personally identifiable information in query results',
    enabled: true,
  },
  {
    id: 'gov-003',
    label: 'AI Trace Logging',
    description: 'Log all AI-generated queries with full execution trace for audit',
    enabled: true,
  },
  {
    id: 'gov-004',
    label: 'RLS Auto-Enforcement',
    description: 'Automatically apply row-level security filters based on user context',
    enabled: true,
  },
];
