import type { SemanticEntity, EntityRelationship, CertifiedMetric } from './types';

// ─── Semantic Entities ──────────────────────────────────────────────────────

export const entities: SemanticEntity[] = [
  {
    id: 'customer',
    name: 'Customer',
    recordCount: 12847,
    color: '#2563EB',
    dimensions: ['customer_id', 'name', 'email', 'plan', 'region', 'signup_date'],
    measures: ['lifetime_value', 'total_spend', 'months_active'],
  },
  {
    id: 'subscription',
    name: 'Subscription',
    recordCount: 15234,
    color: '#16A34A',
    dimensions: ['subscription_id', 'plan_name', 'status', 'billing_cycle', 'start_date'],
    measures: ['amount', 'discount', 'net_amount'],
  },
  {
    id: 'invoice',
    name: 'Invoice',
    recordCount: 84521,
    color: '#D97706',
    dimensions: ['invoice_id', 'status', 'currency', 'due_date', 'paid_date'],
    measures: ['total', 'tax', 'amount_paid', 'balance_due'],
  },
  {
    id: 'support_ticket',
    name: 'Support Ticket',
    recordCount: 6392,
    color: '#7C3AED',
    dimensions: ['ticket_id', 'priority', 'category', 'status', 'created_at'],
    measures: ['resolution_time_hours', 'response_time_hours', 'satisfaction_score'],
  },
  {
    id: 'product_event',
    name: 'Product Event',
    recordCount: 2341876,
    color: '#EC4899',
    dimensions: ['event_id', 'event_type', 'feature', 'platform', 'timestamp'],
    measures: ['session_duration', 'event_count', 'page_views'],
  },
];

// ─── Entity Relationships ───────────────────────────────────────────────────

export const relationships: EntityRelationship[] = [
  {
    source: 'customer',
    target: 'subscription',
    type: 'has_many',
    label: 'has_many subscriptions',
  },
  {
    source: 'subscription',
    target: 'invoice',
    type: 'has_many',
    label: 'has_many invoices',
  },
  {
    source: 'customer',
    target: 'support_ticket',
    type: 'has_many',
    label: 'has_many tickets',
  },
  {
    source: 'customer',
    target: 'product_event',
    type: 'has_many',
    label: 'has_many events',
  },
  {
    source: 'subscription',
    target: 'customer',
    type: 'belongs_to',
    label: 'belongs_to customer',
  },
  {
    source: 'invoice',
    target: 'subscription',
    type: 'belongs_to',
    label: 'belongs_to subscription',
  },
];

// ─── Certified Metrics ──────────────────────────────────────────────────────

export const certifiedMetrics: CertifiedMetric[] = [
  {
    id: 'mrr',
    name: 'MRR',
    formula: 'SUM(subscriptions.amount) WHERE status = active',
    sql: "SELECT SUM(amount) FROM subscriptions WHERE status = 'active'",
    owner: 'Finance Team',
    certifiedDate: '2024-01-15',
    aiUsageCount: 1284,
    timeDimension: 'month',
    synonyms: ['Monthly Recurring Revenue', 'Recurring Revenue'],
    aiPolicy: 'Always use certified definition',
  },
  {
    id: 'arr',
    name: 'ARR',
    formula: 'MRR × 12',
    sql: "SELECT SUM(amount) * 12 FROM subscriptions WHERE status = 'active'",
    owner: 'Finance Team',
    certifiedDate: '2024-01-15',
    aiUsageCount: 892,
    timeDimension: 'year',
    synonyms: ['Annual Recurring Revenue', 'Annualized Revenue'],
    aiPolicy: 'Always use certified definition',
  },
  {
    id: 'churn_rate',
    name: 'Churn Rate',
    formula: 'Churned Customers / Total Customers at Period Start × 100',
    sql: "SELECT COUNT(CASE WHEN status = 'churned' THEN 1 END)::float / COUNT(*)::float * 100 FROM customers WHERE cohort_month = :period",
    owner: 'Growth Team',
    certifiedDate: '2024-02-01',
    aiUsageCount: 743,
    timeDimension: 'month',
    synonyms: ['Customer Churn', 'Attrition Rate', 'Logo Churn'],
    aiPolicy: 'Always use certified definition',
  },
  {
    id: 'nrr',
    name: 'NRR',
    formula: '(Starting MRR + Expansion - Contraction - Churn) / Starting MRR × 100',
    sql: "SELECT (starting_mrr + expansion_mrr - contraction_mrr - churned_mrr) / starting_mrr * 100 FROM revenue_metrics WHERE period = :period",
    owner: 'Finance Team',
    certifiedDate: '2024-01-20',
    aiUsageCount: 621,
    timeDimension: 'month',
    synonyms: ['Net Revenue Retention', 'Net Dollar Retention', 'NDR'],
    aiPolicy: 'Always use certified definition',
  },
  {
    id: 'active_users',
    name: 'Active Users',
    formula: 'COUNT(DISTINCT user_id) WHERE last_active >= NOW() - 30 days',
    sql: "SELECT COUNT(DISTINCT user_id) FROM product_events WHERE timestamp >= NOW() - INTERVAL '30 days'",
    owner: 'Product Team',
    certifiedDate: '2024-02-10',
    aiUsageCount: 534,
    timeDimension: 'day',
    synonyms: ['MAU', 'Monthly Active Users', '30-Day Active'],
    aiPolicy: 'Use certified definition; specify time window',
  },
  {
    id: 'arpa',
    name: 'ARPA',
    formula: 'MRR / Total Active Customers',
    sql: "SELECT SUM(amount) / COUNT(DISTINCT customer_id) FROM subscriptions WHERE status = 'active'",
    owner: 'Finance Team',
    certifiedDate: '2024-02-15',
    aiUsageCount: 412,
    timeDimension: 'month',
    synonyms: ['Average Revenue Per Account', 'ARPU', 'Revenue Per Customer'],
    aiPolicy: 'Always use certified definition',
  },
  {
    id: 'expansion_revenue',
    name: 'Expansion Revenue',
    formula: 'SUM(upgrade_amount) for period',
    sql: "SELECT SUM(amount_change) FROM subscription_changes WHERE change_type = 'upgrade' AND changed_at >= :period_start AND changed_at < :period_end",
    owner: 'Growth Team',
    certifiedDate: '2024-03-01',
    aiUsageCount: 287,
    timeDimension: 'month',
    synonyms: ['Expansion MRR', 'Upsell Revenue', 'Upgrade Revenue'],
    aiPolicy: 'Always use certified definition',
  },
  {
    id: 'support_volume',
    name: 'Support Volume',
    formula: 'COUNT(tickets) for period',
    sql: "SELECT COUNT(*) FROM support_tickets WHERE created_at >= :period_start AND created_at < :period_end",
    owner: 'Support Team',
    certifiedDate: '2024-03-05',
    aiUsageCount: 198,
    timeDimension: 'week',
    synonyms: ['Ticket Count', 'Support Requests', 'Help Desk Volume'],
    aiPolicy: 'Use certified definition; can filter by priority',
  },
];
